### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by definedw** [CurtisCBS/CurtisCBS.github.io#2]
刚看你的blog，但comment直接跳转到这里来了。
我前几天也搭建了自己的VPN，用的是跟你差不多的教程，但是翻墙的结果，使用shadowsocksx在mac上死活都不能用，在windows就可以正常使用。如果你有相关的经验或者你知道相关的知识，希望可以与你一起探讨。
另外我发现你建站的方式比较美观简约，也希望可以和你一起探讨一下。
如有打扰，敬请见谅！
附上我的git:https://github.com/definedw/alpha/issues/1

**Comment by CurtisCBS** [comment]
不能用的话查看配置是否正确，或者是否有其他浏览器也做了代理的白名单或情景之类的。
如果你说的建站是指blog的话，推荐你试试jekyll
